<?php

/**
 * @file
 * Commerce crefopay module.
 */

declare(strict_types = 1);

use CrefoPay\Library\Config;
use Drupal\commerce_order\Entity\OrderInterface;

/**
 * Implements hook_theme().
 */
function commerce_crefopay_theme() {
  return [
    'crefopay_payment' => [
      'variables' => [
        'order' => NULL,
        'allowed_methods' => [],
        'additional_information' => [],
        'allowed_instruments' => [],
      ],
    ],
  ];
}

function commerce_crefopay_subscripton_plans_options() {
  /** @var \Drupal\commerce_crefopay\SubscriptionManager $subscription_manager */
  $subscription_client = \Drupal::service('commerce_crefopay.subscription_client');
  $plans = $subscription_client->getSubscriptionPlans();
  return $plans;
}

/**
 * Implements hook_crefopay_config_alter().
 */
function commerce_crefopay_crefopay_config_alter(Config $config, array $context) {
  $order = $context['order'] ?? NULL;
  /** @var \Drupal\commerce_payment\Entity\PaymentGatewayInterface $payment_gateway */
  if (!empty($order) && $order->hasField('payment_gateway') && $payment_gateway = $order->payment_gateway->entity) {
    $plugin_config = $payment_gateway->getPluginConfiguration();
    if (strpos($payment_gateway->getPluginId(), 'crefopay') !== FALSE && !empty($payment_gateway->getPluginConfiguration()['store_id'])) {
      $config->setData(['storeID' => $payment_gateway->getPluginConfiguration()['store_id']]);
    }
  }
}
